version: '3.3'

services:
  firebird259:
    image: jacobalberty/firebird:2.5.9-ss
    expose:
      - 3050/tcp
    ports:
      - "3050:3050"
    volumes:
      - /mnt/disk2/databases/2.5.9:/firebird/data
    environment:
      - ISC_PASSWORD=masterkey
      - FIREBIRD_USER=sysdba

  firebird25:
    image: jacobalberty/firebird:2.5-ss
    expose:
      - 3050/tcp
    ports:
      - "3051:3050"
    volumes:
      - /mnt/disk2/database/2.5:/firebird/data
    environment:
      - ISC_PASSWORD=masterkey
      - FIREBIRD_USER=sysdba

  firebird30:
    image: jacobalberty/firebird:3.0.6
    expose:
      - 3050/tcp
    ports:
      - "3052:3050"
    volumes:
      - /mnt/disk2/databases/3.0:/firebird/data
    environment:
      - ISC_PASSWORD=masterkey
      - FIREBIRD_USER=SYSDBA
  
  firebird40:
    image: jacobalberty/firebird:4.0
    expose:
      - 3050/tcp
    ports:
      - "3053:3050"
    volumes:
      - /mnt/disk2/databases/4.0:/firebird/data
    environment:
      - ISC_PASSWORD=masterkey
      - FIREBIRD_USER=SYSDBA
  
  redis:
    image: redis:alpine
    expose:
      - 6379/tcp
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - 5672:5672
      - 15672:15672

